spring.application.name=civicpulse

#Database connection
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=update

# Spring Data Redis Configuration
spring.data.redis.host=${RADIS_HOST}
spring.data.redis.port=${REDIS_PORT}

#Brevo API
brevo.api.key=${BREVO_API_KEY}

#JWT secret key
jwt.secret=${JWT_SECRET}
