spring.application.name=civicpulse

#Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/CivicPulse
spring.datasource.username=postgres
spring.datasource.password=1808
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Data Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Brevo API
brevo.api.key=${BREVO_API_KEY}
