spring.application.name=civicpulse
spring.security.user.name=user
spring.security.user.password=1234

#Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/CivicPulse
spring.datasource.username=postgres
spring.datasource.password=1808
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#mail for otp
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=e7e1e8aaf1f75f
spring.mail.password=c59fbd663f57e6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Spring Data Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
